### ISSUE TITLE
Relative paths to images inside markdown are broken when doing an include

### ISSUE THREAD

**Issue by joerick** [mondeja/mkdocs-include-markdown-plugin#1]
Hello @mondeja ! I haven't touched this module in over a year and as soon as you take it over, I have a feature request! :)

I'm including another section from our README into the docs. This section contains images, in the `![](path_to_image)` format. 

**README.md**
```md
....
<!--examples-start-->
![](docs/assets/example.png)
<!--examples-end-->
...
```

**docs/examples.md**
```md
{%
   include-markdown "../README.md"
   start="<!--examples-start-->"
   end="<!--examples-end-->"
%}
```

But the trouble is, when the snippet from README.md is included, the relative path breaks because it's relative to a different file. I guess the same problem would occur for relative hyperlinks, too.

I'm wondering about a flag that can be used on include-markdown, which would rewrite URLs to be relative to the inclusion location. So something like 
```md
{%
   include-markdown "../README.md"
   start="<!--examples-start-->"
   end="<!--examples-end-->"
   rewrite_relative_urls=true
%}
```

What do you think?

**Comment by mondeja** [comment]
I think that this makes sense, but `rewrite_relative_urls` would be the default behaviour, not? And the flag must be setted if it is not intended to rewrite link targets.

**Comment by joerick** [comment]
Hm, yes. I suppose it's pretty safe to rewrite the URLs, as long as they're relative, so it could be the default. 

Do you want to work on an implementation, or would you prefer I submit a PR?

**Comment by mondeja** [comment]
Since you are working in the problem yet, I think that would be faster if you can sumbit it. Let me know if you have problems with the implementation and I will help.
