### ISSUE TITLE
[wish] Option to omit YAML frontmatter when including an .md

### ISSUE THREAD

**Issue by twardoch** [mondeja/mkdocs-include-markdown-plugin#110]
When I include a full Markdown file that has YAML frontmatter (metadata) in another Markdown file, the plugin copies the YAML which becomes invalid HTML

It would be wonderful if there was a simple option to skip the YAML frontmatter when including an .md file

**Comment by twardoch** [comment]
It’s not obvious how you’d do it. Generic Markdown with YAML frontmatter is like: 

```
---
title: 'Some title'
someoption:
    somevalue: 1
---

# Some H1 heading but not always

Some text
```

Strictly speaking, I could use something like 

```
start="# "
```

but then the plugin "eats" the heading marker, so in the included file the first heading is treated as normal text. 

For now, I’m doing something like this: 

```
---
title: 'Some title'
someoption:
    somevalue: 1
---

# Some H1 heading but not always

<!--body-->

Some text
```

and I’m using `<!--body-->` as the `start` marker. I’m flexible in where I put the marker — and it works. 

But simple Markdown inclusion without a marker should still work. In the end, the YAML frontmatter is a standard feature of Markdown files used in MkDocs. And this frontmatter should pretty much always be ignored if I include a file. No?

**Comment by mondeja** [comment]
What about [page metadata](https://www.mkdocs.org/dev-guide/themes/#pagemeta) and [Multimarkdown front-matter](https://www.mkdocs.org/user-guide/writing-your-docs/#multimarkdown-style-meta-data), should we support it too? Also, what is the difference between adding a comment after the front-matter and adding an option which is disabled by default to skip the frontmatter? I'm not sure about what profit would it bring to the plugin.

**Comment by mondeja** [comment]
As a workaround, if you always follow the next consistent format:

```yaml
---
foo: bar
---

Some content.
```

letting one empty line after the frontmatter, you can use `---\n\n` as the start delimiter:

```jinja
{%
   include-markdown "../other-file.md"
   start="---\n\n"
%}
``` 

but if your frontmatter is bad formatted will not work:

```yaml
---

foo: bar
---
Some content.
```

You can use [`options.frontMatter` with `markdownlint`](https://github.com/DavidAnson/markdownlint/blob/main/README.md#optionsfrontmatter) to enforce the format and avoid this kind of errors.

**Comment by mondeja** [comment]
I think that could be great to document the workarounds for this problem.
