### ISSUE TITLE
[Feature-Request] Including of other files in .yml

### ISSUE THREAD

**Issue by FloKnapp** [mondeja/mkdocs-include-markdown-plugin#111]
**User-Story**
As a user, i'd like to separate the navigation sections into separate .yml files. This would help me when updating or extending the navigation with navigation items. In bigger applications it'd be confusing to maintain hundreds of lines of indent-dependent code.

**Example**
Currently, everything has to be defined in one file (mkdocs.yml).
```
nav:
    - Project 1
        - 1. Introduction: 'ref-to-markdown-file.md'
        - 2. Quickstart: 'ref-to-markdown-file.md'
        - 3. Components:
            - 3.1 Example component
            - 3.2 Another example component
            - //...
    - Project 2
        - 1. Introduction: 'ref-to-markdown-file.md'
        - 2. Quickstart: 'ref-to-markdown-file.md'
        - 3. Components:
            - 3.1 Example component
            - 3.2 Another example component
            - //...
    - Project 3
        - 1. Introduction: 'ref-to-markdown-file.md'
        - 2. Quickstart: 'ref-to-markdown-file.md'
        - 3. Components:
            - 3.1 Example component
            - 3.2 Another example component
            - //...
```

It would be great if i'm able to do this:
```
nav:
    - Project 1: !include 'project-1/structure.yml'
    - Project 2: !include 'project-2/structure.yml'
    - Project 3: !include 'project-3/structure.yml'
```

Is something like this possible?

**Comment by mondeja** [comment]
This is impossible to accomplish with the current plugin system of Mkdocs, there is not a [global event](https://www.mkdocs.org/dev-guide/plugins/#global-events) to alter alter the configuration before validating it. Anyways, this is out of the scope of this project.

It is almost possible with [Configuration inheritance](https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance) with standalone Mkdocs, but not, quoting the documentation:

> As the [nav](https://www.mkdocs.org/user-guide/configuration/#nav) configuration is made up of nested lists, this means that you cannot merge navigation items. Of course, you can replace the entire nav configuration with a new one. However, it is generally expected that the entire navigation would be defined in the primary configuration file for a project.

So I would suggest you to open the issue in Mkdocs itself.
