### ISSUE TITLE
Weird behavior when using include-markdown on the same file

### ISSUE THREAD

**Issue by Archmonger** [mondeja/mkdocs-include-markdown-plugin#113]
If I have a file `example.md` and I attempt to use `include-markdown` to fetch from `example.md` (same file), then some odd behavior occurs.

Seems like the include works for the most part, except for a trailing `" end="` printout.

![image](https://user-images.githubusercontent.com/16909269/181116858-4626387c-06d6-41ac-a065-02347e2a144b.png)

Here's the relevant snippets from the markdown doc

```md
<!--orm-questions-start-->

??? question "Can I make ORM calls without hooks?"

    Due to Django's ORM design, database queries must be deferred using hooks. Otherwise, you will see a `SynchronousOnlyOperation` exception.

    This may be resolved in a future version of Django with a natively asynchronous ORM.

??? question "What is an "ORM"?"

    A Python **Object Relational Mapper** is an API for your code to access a database.

    See the [Django ORM documentation](https://docs.djangoproject.com/en/dev/topics/db/queries/) for more information.

<!--orm-questions-end-->


. . .


??? question "Can `use_mutation` trigger refetch of a `use_query`?"

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incididunt 

{% include-markdown "hooks.md" start="<!--orm-questions-start-->" end="<!--orm-questions-end-->" %}
```

**Comment by mondeja** [comment]
The file is trying to include itself, so is matching both `<!--orm-questions-start-->` and `<!--orm-questions-end-->`, so it is including the `" end="` part in a second inclusion. Note that `include-markdown` includes all parts located between matching `start` and `end` in a document, so this is the expected behaviour.

Other possible behaviour is to raise a `MaximumRecursionError` here trying to replace all matches before the inclusion, but is preferable that the document can be included without doing the replacements.

**Comment by Archmonger** [comment]
A programmatic alternative could be to refuse any matches contained within a jinja-style tag, which would allow for self inclusions without a separate file.

```jinja
<!--- Refuse anything that regex matches tags like this --->
{%  ....  %}
```

With mkdocs, there is no pragmatic way of creating a file for the sole purpose of referencing inclusion tags. While it can be done, it'll leave a pesky warning behind that the file is unused.

**Comment by mondeja** [comment]
You can create a `docs/src/` and a `docs/includes` directory and set `docs_dir` to `docs/src` in the configuration to avoid the warning.
