### ISSUE TITLE
Feature request: nested includes

### ISSUE THREAD

**Issue by deep9** [mondeja/mkdocs-include-markdown-plugin#12]
For the current scenario I have nested includes - and there is no simple (or convenient) way around it.

Would it be possible to support it?

Thanks.

**Comment by mondeja** [comment]
Added in v2.4.0

**Comment by deep9** [comment]
@mondeja Sorry to bother again, it seems that the included file url can't be relative to the file it is used in, is that correct? That kind of makes it hard to use, if the main included file is used in different levels of the project.

**Comment by mondeja** [comment]
Thank you for report it! It's fixed in v2.6.1
