### ISSUE TITLE
Feature request: Global config settings

### ISSUE THREAD

**Issue by cncook001** [mondeja/mkdocs-include-markdown-plugin#121]
It would be great to set a global flag to change some of the default settings.

e.g. Whenever I add "include-markdown", I want to automatically set these as defaults as well:

comments=false
trailing-newlines=true

**Comment by mondeja** [comment]
Released in [v3.8.0](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.8.0).
