### ISSUE TITLE
Code formatting question

### ISSUE THREAD

**Issue by cncook001** [mondeja/mkdocs-include-markdown-plugin#123]
I have a file called "test.md"

```
1.  This is the first number line

1.  {%
       include-markdown "./includes/content_chunk_with_code.md"
    %}

1.  If everything works as expected this should be number 3
```

The contents of "./includes/content_chunk_with_code.md" is this

```
This content chunk contains code

\```
This is my example
It is a code block
\```

With some text after it
```

The code block renders all the way to the left margin, and it shows on one line, not two. (Ignore/remove the "\\" in the example content chunk, I had to add it to this issue allowing the back ticks to show up).

**Comment by cncook001** [comment]
<img width="531" alt="Screen Shot 2022-09-16 at 6 37 47 AM" src="https://user-images.githubusercontent.com/1742271/190626634-dea00165-be56-43b9-8344-5d0ec201cbfb.png">

**Comment by mondeja** [comment]
Fixed in [v3.8.1](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.8.1).

**Comment by cncook001** [comment]
Thanks for the backtips tip.  I created a test site here to check your fix, https://github.com/cncook001/mkdocs-test. It still seems to be an issue.

**Comment by mondeja** [comment]
> Thanks for the backtips tip. I created a test site here to check your fix, https://github.com/cncook001/mkdocs-test. It still seems to be an issue.

I can't replicate it, could you share a minimal reproducible example?
