### ISSUE TITLE
Allow for indented "info" boxes

### ISSUE THREAD

**Issue by cncook001** [mondeja/mkdocs-include-markdown-plugin#131]
Using the extension "admonition" we are able to add "highlight boxes" to our site.

<img width="820" alt="Screen Shot 2022-10-27 at 10 07 33 AM" src="https://user-images.githubusercontent.com/1742271/198307885-560e6516-b0b8-4be8-ab3d-071fe96b068b.png">

Is there a way to allow "indented info boxes"?

I have a test site here to show what I did: https://github.com/cncook001/mkdocs-test

https://github.com/cncook001/mkdocs-test/blob/main/mkdocs/docs/info-test.md

**Comment by mondeja** [comment]
You can include whatever content in whatever indent, just indent the `{% include-markdown "./includes/chunk_with_info.md" %}` line.
