### ISSUE TITLE
Include from URL

### ISSUE THREAD

**Issue by alexzanderr** [mondeja/mkdocs-include-markdown-plugin#138]
hello

i am trying to do something like this

```markdown

# included from gtihub url

{%
    include-markdown "https://raw.githubusercontent.com/timescale/timescaledb/main/README.md"
%}
```

is it possible? i mean its not (this way), because i've tested it and its not working, but if it is possible how can i do this?

if not, i would like to request a feature for this to be implemented.

thanks in advance.

**Comment by mondeja** [comment]
I'm open to this idea if someone wants to implement it, but the requests must be cached to work offline in subsecuent ones. I don't have motivation to implement it as I don't need it.
