### ISSUE TITLE
Drop Python3.7 support

### ISSUE THREAD

**Issue by mondeja** [mondeja/mkdocs-include-markdown-plugin#142]

**Comment by Monyer** [comment]
requires-python = ">=3.7,<3.12"

<3.12 is bad, and not necessary.

because of this, I must change my dependencies from ^3.10 to ^3.10,<3.12

**Comment by mondeja** [comment]
So you are totally sure that all your dependencies and your code will work with Python3.12 without changing anything? Why is poetry giving its users that false sense of security? They never use Python-versioned wheels?

**Comment by Monyer** [comment]
Thx for the reply.

I fix it by using `mkdocs-include-markdown-plugin = { version = "^4.0", python = "^3.8,<3.12" }`
