### ISSUE TITLE
Add 'preserve_includer_indent' argument to 'include' directive

### ISSUE THREAD

**Issue by mondeja** [mondeja/mkdocs-include-markdown-plugin#15]

**Comment by mondeja** [comment]
Added in v2.5.0

**Comment by joerick** [comment]
Nice, I was about to open a PR for this and then I saw you'd already done it. I do wonder if it should be on by default, too.

**Comment by mondeja** [comment]
> I do wonder if it should be on by default, too.

Seems reasonable, I'm not sure why I've setted the default value in `true` from the beggining. Let me a few minutes, I upload the commit and launch it in v2.8.0.

**Comment by mondeja** [comment]
Done in [v2.8.0](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v2.8.0)

**Comment by joerick** [comment]
Cool! Nice one @mondeja 👍
