### ISSUE TITLE
Is there a way to include markdown from a remote url?

### ISSUE THREAD

**Issue by clubanderson** [mondeja/mkdocs-include-markdown-plugin#158]
I would like to include an md file from a blob in a remote GitHub repo. Like https://GitHub.com/ccc/ddd/blob/main/mailbox.md

**Comment by mondeja** [comment]
Duplicate of #138

**Comment by clubanderson** [comment]
how do I compile and include my version of this plugin (for testing) into mkdocs?  I would like to try and build this functionality into a PR
