### ISSUE TITLE
Dash `-` is an invalid symbol within HTML templates

### ISSUE THREAD

**Issue by Archmonger** [mondeja/mkdocs-include-markdown-plugin#175]
### Discussed in https://github.com/mondeja/mkdocs-include-markdown-plugin/discussions/174

<sup>Originally posted by **Archmonger** August 27, 2023</sup>
I am trying to [override the `home.html` template](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks) within `mkdocs-material` by following the built-in [`.overrides/home.html` template](https://github.com/squidfunk/mkdocs-material/issues/1996#issuecomment-1436530062).

Although I need to write HTML for this override, there are a few things that are slightly easier to do in markdown (such as syntax highlighted code blocks).

Within my `home.html` override, I have the following block of code:

```jinja
{% block tabs %}
{% include-markdown "test.md" %}
{% endblock %}
```

But it doesn't appear to work because a dash `-` in the `include-markdown` template tag is an invalid Jinja symbol.

Having a dash in the template tag name is invalid Jinja syntax to begin with, so I'm surprised it works within mkdocs markdown at all.

**Comment by mondeja** [comment]
> Having a dash in the template tag name is invalid Jinja syntax to begin with, so I'm surprised it works within mkdocs markdown at all.

Jinja2 is only executed against template pages, not Markdown pages. mkdocs-include-markdown-plugin is executed in the `on_page_markdown` event. See [this lines in Mkdocs](https://github.com/mkdocs/mkdocs/blob/94e9f17cd7a69e70c18ae282d55ba2f34f93c542/mkdocs/commands/build.py#L339C1-L343). Please, don't use mkdocs-include-markdown-plugin against template pages, it is not intended to work there.

**Comment by Archmonger** [comment]
As a side note, somehow the `include` tag does work properly.

**Comment by mondeja** [comment]
> As a side note, somehow the `include` tag does work properly.

Works if you pass parameters to it?

**Comment by Archmonger** [comment]
Yup. Perhaps it's because `mkdocs-material` renders itself within the `mkdocs` rendering stack?

Not entirely sure, but that makes me think there's a chance the `include-markdown` tag would just work if it didn't have a dash in it.

**Comment by mondeja** [comment]
Ok, I'm not tested it but if someone wants to make the dash (`-`) optionally replaceable by an underscore (`_`) feel free to open the PR and I'll accept it. The change doesn't seem too much intrusive if it would make the plugin work for templates.

But I still seem this like a really really strange usage.

**Comment by Archmonger** [comment]
Agreed that the usage is pretty niche. Not too many people manually edit their HTML templates to begin with. Plus I don't even know if `include-markdown` would actually result in the markdown being rendered properly.

I will test it out and let you know.

**Comment by mondeja** [comment]
TBH, I'm really impressed that the arguments are ignored by Jinja, but could be. Note that could broke in a future release without notice in the plugin part. Also, I don't understand why are you using a plugin to build templates, that sounds mind blowing for me and I didn't tested anything of this by myself, just trusting you until the review of the possible future feature.

**Comment by Archmonger** [comment]
To clarify, I'm not exactly using this plugin to build the templates themselves. The templates are a part of `mkdocs-material`'s customization featurs. I'm just overriding their sub-templates. Based on what I could gleam, I don't believe any of `mkdocs-material`'s rendering logic is post-build. I can't confirm though since I'm not too deeply rooted in that project.

But as the original post says, it would be really useful to use markdown to render code blocks. Although I'm being pigeonholed into writing HTML to generate my homepage (`index.html`), I'd ideally like my code block rendering behavior to match whatever mkdocs is doing.

I could just manually write code blocks in HTML, but that isn't very resilient to future mkdocs styling changes or rendering logic updates.

**Comment by Archmonger** [comment]
Realizing now that the `include` tag that is exposed at this level is actually the Jinja2 [built-in `include` tag](https://jinja.palletsprojects.com/en/3.1.x/templates/#include).

Since it's uncertain whether this plugin can even operate within this weird context, I will close this issue.
