### ISSUE TITLE
WARNING log variables not binded

### ISSUE THREAD

**Issue by mirk8s** [mondeja/mkdocs-include-markdown-plugin#183]
The following WARNING is logged, but no variable significant value is shown:

`WARNING -  plugins.mkdocs_include_markdown_plugin: Delimiter {delimiter_name} '{delimiter_value}' of '{directive}' directive at {relative_path}:{line_number} not detected in the file{plural_suffix} {readable_files_to_include}`

So I understand that this warns about a mistake in using include delimiters between importing and imported files, but it is not helpful to locate the issue.

**Comment by mondeja** [comment]
Thanks for the report. Fixed by [v6.0.4](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v6.0.4).
