### ISSUE TITLE
absolute URLs to include markdowns are sourced inside `docs/`

### ISSUE THREAD

**Issue by MarcBresson** [mondeja/mkdocs-include-markdown-plugin#185]
Hello, 

I am trying to include a markdown file in another from its absolute URL. The URL i'm trying to include is `"docs/includes/blabla.md"` from a file in `"docs/other/example.md"`, but it fails.

To make it work, I must remove the `docs/` folder. It gives: `"includes/blabla.md"`.

Is it a configuration issue on my end or should the example given in the readme.md of this repo be updated?

**Comment by mondeja** [comment]
> I am trying to include a markdown file in another from its absolute URL.

Please, share the example code. If is an absolute URL should work. How is the URL?

**Comment by mondeja** [comment]
Yeah, that's correct. The examples in the documentation are not updated. Do you want to open a PR to fix them?
