### ISSUE TITLE
Include a table as part of a list item

### ISSUE THREAD

**Issue by panicseal** [mondeja/mkdocs-include-markdown-plugin#192]
Hello, thank you for this great mkdocs plugin!

I'm trying to include a table in different contexts, and one of them is a list. 
This breaks the table rendering.

file `tbl.md`
```markdown
| A   | B   |
|-----|-----|
| foo | bar | 
```

file `main.md`
```markdown
### Table included as part of a list item:
1. A list entry
1. Item with table

    {%
      include-markdown "./tbl.md"
    %}

1. Another list entry

### Expected output:
1. A list entry
1. Item with table

    | A   | B   |
    |-----|-----|
    | foo | bar |

1. Another list entry
```

See attached screenshot with rendered result:
![firefox_2024-01-29_14-29-16](https://github.com/mondeja/mkdocs-include-markdown-plugin/assets/153102456/71ba29d3-a78f-4c5d-9184-b02f74322588)

I hope this can be fixed / implemented.
Thank you very much for your time and effort to provide this plugin!

**Comment by mondeja** [comment]
Just use `comments=false`:

```
{%
    include-markdown "./tbl.md"
    comments=false
%}
```

Comments are breaking the parsing of the list item. Can be disabled globally in [Global configuration](https://github.com/mondeja/mkdocs-include-markdown-plugin?tab=readme-ov-file#configuration).

**Comment by panicseal** [comment]
Thank you very much for the swift reply and solution.
I wish you all the best.
