### ISSUE TITLE
Unable to include content over SSL

### ISSUE THREAD

**Issue by karl-johan-grahn** [mondeja/mkdocs-include-markdown-plugin#198]
When including content over SSL such as:
```yaml
{% include "https://raw.githubusercontent.com/NordMart/review-api/main/.tekton/git_clone.yaml" %}
```

mkdocs fails with:
```sh
ERROR   -  Error reading page 'page.md': <urlopen
           error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate
           (_ssl.c:997)>

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

Do we need to use something like:
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

in https://github.com/mondeja/mkdocs-include-markdown-plugin/blob/master/src/mkdocs_include_markdown_plugin/process.py?

**Comment by mondeja** [comment]
You don't have installed SSL certificates on your machine.

**Comment by karl-johan-grahn** [comment]
I can curl the url without problem

**Comment by mondeja** [comment]
Ah wait... could you paste the url/path that includes a `page.md` file? 

> ```
> ERROR   -  Error reading page 'page.md': <urlopen
> ```

The problem seems to be there, not in the link that you've shared.

**Comment by karl-johan-grahn** [comment]
An example PR is here https://github.com/stakater/saap-docs/pull/218/files

It actually builds the container and works as expected:
![Screenshot 2024-03-12 at 15 24 41](https://github.com/mondeja/mkdocs-include-markdown-plugin/assets/6355577/43790c30-ba3d-4130-ab3d-6f0eaaca02a8)

So it is only an issue when I run mkdocs locally, I use version 1.5.3 on MacOS 🤔

**Comment by karl-johan-grahn** [comment]
We have the `mkdocs.yml` file and it just includes the file as any md file.

**Comment by karl-johan-grahn** [comment]
`mkdocs.yml` > `page.md` > includes the external yaml

**Comment by karl-johan-grahn** [comment]
Should be able to replicate it by:
1. Fork https://github.com/stakater/saap-docs
2. Checkout `embed-external-files`
3. Install mkdocs through https://www.mkdocs.org/user-guide/installation/
4. mkdocs serve

**Comment by karl-johan-grahn** [comment]
I actually get the same error if I use your example:

```sh
/Users/<username>/git/mkdocs-include-markdown-plugin/examples/http-cache $ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
ERROR   -  Error reading page 'README.md': <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
           unable to get local issuer certificate (_ssl.c:997)>

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by mondeja** [comment]
You have a Python build without SSL certificates linked on your local MacOS, that's why `curl` works. Reinstall Python, that should fix it.

**Comment by mondeja** [comment]
Additionally, it could exist a bug on MacOS regarding relative links but that's something very very unlikely and no one has complained about it before when this plugin has 250k monthly downloads. I don't have MacOS so I can't check it.

Your proposed solution is to remove SSL for all users, something totally crazy.
