### ISSUE TITLE
Blank code line in between included files

### ISSUE THREAD

**Issue by julianx** [mondeja/mkdocs-include-markdown-plugin#20]
I am including multiple files from a main file, but there's an odd behavior that adds a blank code-block line between each of the different imported md file contents. Those md files have no extra spaces prior or after the boundary blocks, thus it's weird that it's happening; however, the issue went away by setting multiple include-markdown statements together on a same line. Weirdly enough, the issue did not return after splitting that long single line into multiple lines again, as if there had been bogus characters somewhere in between.

I'm creating this issue to let everyone know I got to get rid of them by setting the includes in a single line and then splitting them into two again.

initial main-file.md:

```
{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}
{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}
```

Modified main-file.md:
```
{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}
```

Final main-file.md:
```
{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}
{% include-markdown "1-introduction.md" start="<!--begin-block-->" end="<!--end-block-->" %}
```

**1-introduction.md**:
```
<!--begin-block-->
#Introduction

sample text.
<!--end-block-->
```

**mkdocs.yml**:
```
plugins:
  - search
  - include-markdown
```

**Comment by mondeja** [comment]
I don't understand you. What are you trying to do?

**Comment by julianx** [comment]
I apologize, it seems my description was not clear. I improved it. Basically, the plugin works great but I got some extra (empty, undesired) content in between imported files.

**Comment by mondeja** [comment]
Keep in mind that the newlines after the `<!--begin-block-->` and the newline before the `<!--end-block-->` comments are included also. Have you tried including next content in `1-introduction.md` file?

```markdown
<!--begin-block-->#Introduction

sample text.<!--end-block-->
```
