### ISSUE TITLE
Add a configuration option to filter out license headers on inclusion

### ISSUE THREAD

**Issue by vorburger** [mondeja/mkdocs-include-markdown-plugin#225]
I use `start` to manually filter out License headers, e.g. [here](https://github.com/enola-dev/enola/commit/1fa9fe41077852256ffc2eadee41b037f8ed48f9), like this (see [`picasso.yaml`](https://github.com/enola-dev/enola/blob/1f3757ad5733a1651fef9b73d90bed1bdbd164e9/test/picasso.yaml#L1)):

    ```yaml
    {% include "../../../test/picasso.yaml" start="# limitations under the License.\n" %}
    ```

It occurred to me that it would be cool if this had an option to automagically do this.

**Comment by mondeja** [comment]
I think you are an experienced enough programmer to understand why this issue has been closed.
