### ISSUE TITLE
Upgrade to wcmatch 9.0

### ISSUE THREAD

**Issue by epicserve** [mondeja/mkdocs-include-markdown-plugin#226]
I wasn't able to upgrade to wcmatch 9.0 because this project's requirements are pinned to [wcmatch>=8,<9](https://github.com/mondeja/mkdocs-include-markdown-plugin/blob/4406e8a9d786c5a3c5670df390b61a9a1989ceb6/pyproject.toml#L27C4-L27C17).

**Comment by mondeja** [comment]
Thanks for reporting it. Done in [v6.2.2](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v6.2.2).
