### ISSUE TITLE
Accept globs as filenames and include from multiple files

### ISSUE THREAD

**Issue by christo-ph** [mondeja/mkdocs-include-markdown-plugin#49]
Is it possible to include whole (sub)directories with this plugin?

I am looking for a way to include sections from multiple files for "consolidation" of various todos, warnings etc

**Comment by mondeja** [comment]
But what would be the strategy to merge the files, one content after another? I'm not really sure about how this would works. Could you do some feedback about a possible implementation?

**Comment by mondeja** [comment]
Maybe we can change the `filename` positional argument to be considered a glob and expect that the users will use the arguments `start` and `end` to select a snippet from all the files, otherwise all the content of the files will be merged together and included.

**Comment by christo-ph** [comment]
In the past I used often in Confluence the possibility to have one page, which includes all todos from child pages or from the whole wiki.

In my case (I use [Mkdocs](https://www.mkdocs.org) + [material](https://squidfunk.github.io/mkdocs-material/)), I create a documentation with [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) in all pages to know which open points I have to care about.

```console
docs/site/todos.md                # here I check i.e. for <!--todo-start-->
docs/site/warnings.md             # here I check i.e. for <!--warning-start-->
docs/site/<all_other_files>.md    # all files and directories I want to check for specific tags to include
```

In all pages might be one or more warning oder todo admonition which I enclose with the corresponding tags:

```markdown
<!-- prettier-ignore-start -->
<!--warning-start-->
!!! warning "Interface to XYZ"
    The interface to XYZ has to be described. See [Wiki](http://foo.bar).
<!--warning-end-->
<!-- prettier-ignore-end -->
```

which looks like this

<img width="903" alt="image" src="https://user-images.githubusercontent.com/16965068/120934949-d73da180-c700-11eb-9202-af76c4dda3e9.png">

On the site `docs/site/warnings.md` I plan to have all warnings I have created within the project or subdirectory.

I would suggest define those includes like

```markdown
{%
   include-markdown "docs/site/**/*.md"
   show_filename=true
   exclude=[list of files or regex]
%}
```

where this means, search in all subdirectories, show always the filename for every include(group) you found the tag and the possibility to exclude some files if necessary.

**Comment by mondeja** [comment]
I wll probably don't have much time to add this functionality, feel free to create a pull request for this :+1:

**Comment by mondeja** [comment]
I'm revisiting this but I've not enough context to fully understand about the arguments `show_filename` and `link_filename` of your proposal.

> (`show_filename`) show always the filename for every include(group) you found the tag

Where should be shown it? A comment before the inclusion? In that case, is not handled yet by the `comments` argument?

> (`link_filename`) create a link to the source file

I'm not sure about this, would be a link in a text code block after the inclusion? What should be the link format, direct or referenced link? I would opt for not implementing this argument as is not enough consistent and will give problems in the future (more arguments for formatting or whatever).

**Comment by christo-ph** [comment]
Hi @mondeja 

thanks for considering this feature.

Maybe `filename` not the correct term here. The first heading (which is the page name in medics afaik) of the origin should be shown before the included snippet and can be linked, so that with a simple click on that heading you can navigate to it's origin.

**Comment by mondeja** [comment]
> The first heading (which is the page name in medics afaik) of the origin should be shown before the included snippet and can be linked, so that with a simple click on that heading you can navigate to it's origin.

I'm not sure about that because bring more and more questions. For example, these comments or links should be included in nested inclusions? I'm implementing the basic functionality of accepting globs as filenames and the `exclude` argument, but I'm not planning to push trough this more. If someone implements something like which you're proposing solving the problems, the PR will be accepted.

**Comment by mondeja** [comment]
Added in [v3.2.0](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.2.0). Please, open other issues if you want that someone work in the functionalities mentioned, to keep clean the tracker.
