### ISSUE TITLE
Having several start-end tags in included page

### ISSUE THREAD

**Issue by christo-ph** [mondeja/mkdocs-include-markdown-plugin#50]
Having several start-end tags in included page, results in including only the first appearance.

Is it possible to have more than one section included?

```markdown
<!--start-tag-->
## Important Content1
<!--end-tag-->

[unimportant content]

<!--start-tag-->
## Important Content2
<!--end-tag-->

```

**Comment by mondeja** [comment]
Added in [v3.1.0](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.1.0).

**Comment by christo-ph** [comment]
Thanks for your quick support. I tested it and is working as expected.
