### ISSUE TITLE
UTF8 encoding is lost upon including

### ISSUE THREAD

**Issue by yaroslav-khomyak** [mondeja/mkdocs-include-markdown-plugin#74]
Hello,

When I include MD file with language other than english, I lose UTF8 encoding, and text become corrupted.
Onlu english text is included correctly.

**Comment by mondeja** [comment]
And what is the output? Could you share a minimal reproducible example?

**Comment by yaroslav-khomyak** [comment]
Output is like this. English OK, other - messed up

[image: image.png]

Check this mkdocs project

пт, 16 лип. 2021 о 16:17 Álvaro Mondéjar ***@***.***> пише:

**Comment by mondeja** [comment]
Sorry @yaroslav-khomyak, but the image has not been included.

**Comment by yaroslav-khomyak** [comment]
Sorry, I'm not familiar with github

![image](https://user-images.githubusercontent.com/19666423/125960486-631d381c-a545-4b79-ac1f-b8c89eb166cc.png)

[test1.zip](https://github.com/mondeja/mkdocs-include-markdown-plugin/files/6831192/test1.zip)

**Comment by mondeja** [comment]
I can't reproduce it:

![image](https://user-images.githubusercontent.com/23049315/126232787-7f0140e2-daf1-46e7-9297-93d9cee80c7c.png)

Maybe is something related with your environment, what encoding are you using in the terminal that you're executing Mkdocs?

**Comment by mondeja** [comment]
Reproduced with Windows in #75

**Comment by mondeja** [comment]
Fixed in [v3.2.1](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.2.1)

**Comment by yaroslav-khomyak** [comment]
Now, it's working correctly. Thank you!
