### ISSUE TITLE
Markdown links inside code blocks are interpreted

### ISSUE THREAD

**Issue by danvratil** [mondeja/mkdocs-include-markdown-plugin#78]
I seem to have run into a problem when using `{% markdown-include %}` to include a markdown file that contains a code block, which in turn contains something that looks like a valid markdown link (but in fact it's a C++11 lambda definition).

Here's an example. I have a markdown file examples/lambda.md that contains a C++ code snippet, with C++11 lambdas:

`examples/lambda.md`

    This is an example of a C++11 lambda:

    ```cpp
    const auto lambda = []() { .... };
    ````

If I include this markdown file into another document using `{% include-markdown %}`, the `[]()` string in the code block gets interpreted as an empty link

`docs/main.md`

    Hello! Let's learn C++!

    {% include-markdown "../examples/lambda.md" %}

The output then looks like this:

---

Hello! Let's learn C++!

This is an example of a C++11 lambda:

```cpp
const auto lambda = [](../examples) { ... };
```
---

Notice the "../examples" string rendered in the lambda codeblock. I suspect the reason is that `[]()` is a markdown syntax for links, which somehow gets interpreted during the include process, even though it is inside of a code-block. If I change the code example to contain space between `[]` and `()`, then it gets rendered correctly (i.e. no extra strings get injected)

```
const auto lambda = [] () { ... };
```

**Comment by mondeja** [comment]
Thank you for the detailed report. It's fixed and released in [v3.2.2](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.2.2).
