### ISSUE TITLE
Email address is replaced when using in snippet

### ISSUE THREAD

**Issue by deep9** [mondeja/mkdocs-include-markdown-plugin#8]
`[contact us](mailto:info@example.com)` gets replaced as `[contact us](mailto:../../_whateverfolder/info@example.com)` based on where the snippet is located.

**Comment by mondeja** [comment]
Fixed in `2.1.2`, could you check that?

**Comment by deep9** [comment]
@mondeja Thank you for the quick fix 👍

**Comment by mondeja** [comment]
Thank you for the report :pray:
