### ISSUE TITLE
Parts of included markdown file gets incorrectly rendered as code

### ISSUE THREAD

**Issue by guillp** [mondeja/mkdocs-include-markdown-plugin#80]
I found a weird bug while writing documentation for my project:

I have an **index.md** exactly like this:

```
{%
    include-markdown "../README.md"
%}
```

And a **README.md** file that you can find from my repo: https://github.com/guillp/requests_oauth2client/blob/master/README.md

The **index.html** that is generated has the complete top half rendered as code: https://github.com/guillp/requests_oauth2client/blob/00e6ee7f790b158dfd48e4c2c6a750672859c753/index.html

To workaround it, I had to copy/paste the content of README.md into index.md. The generated documentation looks as expected (for reference: https://guillp.github.io/requests_oauth2client/ ).

I am not sure exactly what causes this bug. I tried removing some parts of README.md to see if that had any effect on the render, but did not find the exact location that causes this issue.

Regards,

**Comment by mondeja** [comment]
Thanks for the report, it seems a regression in latest release. You can pin to `mkdocs-include-markdown-plugin==3.2.1` to solve it for now.

**Comment by mondeja** [comment]
Sorry for the inconvenience, it's fixed in [v3.2.3](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v3.2.3).

**Comment by guillp** [comment]
That was quick! Thanks for the fix!
