### ISSUE TITLE
Log warning when failing to find `start` or `end`

### ISSUE THREAD

**Issue by Archmonger** [mondeja/mkdocs-include-markdown-plugin#92]
Currently, if a `start` or `end` delimiter is not detected, the include tag silently handles this. This really ought to be logged via warning.

**Comment by Archmonger** [comment]
Thank you!

**Comment by Archmonger** [comment]
Looks like the latest version no longer warns on missing delimiters. Was this an intentional removal?

If not, sounds like a regression test might be needed.

**Comment by mondeja** [comment]
I'm pretty sure that #177 will fix the problem, but to be totally sure... could you give a try to the branch [regression-92](https://github.com/mondeja/mkdocs-include-markdown-plugin/tree/regression-92)?

You can install it with `python3 -m pip install git+https://github.com/mondeja/mkdocs-include-markdown-plugin@regression-92`

**Comment by Archmonger** [comment]
Confirmed that branch fixes the regression.

**Comment by mondeja** [comment]
Released in [v6.0.1](https://github.com/mondeja/mkdocs-include-markdown-plugin/releases/tag/v6.0.1).

**Comment by Archmonger** [comment]
Thanks for the fix!

This really is an excellent plugin, definitely deserves more attention.
